### PR TITLE
add websocket support

### PR DESCRIPTION
**Pull request by mtmk**

### CODE REVIEW

**Comment by OpenX-Public** [comment]
@mtmk 
Hi,

When this feature is released, will we be able to utilize JWT authentication with it to access WSS Endpoints (Secured WebSockets)?

**Review by piotrpio — APPROVED** [review]
LGTM!

**Review by Jarema — APPROVED** [review]
LGTM!

**Comment by mtmk** [comment]
> @mtmk Hi,
> 
> When this feature is released, will we be able to utilize JWT authentication with it to access WSS Endpoints (Secured WebSockets)?

Hi @OpenX-Public, we should be able to release fairly soon but there is not set schedule. JWT should work with WSS (as the other auth mechanisms).

**Pull request merged**
